version: "3"

services:
  fluentd:
    image: fluent/fluentd:edge
    volumes:
      - ${HOME}/logs:/logs
      - ./etc:/fluentd/etc
    ports:
      - "24225:24224"
      - "24225:24224/udp"
    logging:
      driver: local
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.1 24224 || exit 1" ]
      interval: 10s
      timeout: 10s
      start_period: 5s
