version: "3"

# you have to run this separate from the rest of the tebi images (chicken-egg-problem)
services:
  fluentd:
    image: fluent/fluentd:edge
#    depends_on:
#      opensearch-node:
#        condition: service_healthy
    #image: "${TEBI_REGISTRY_PREFIX:-}fluentd:${TEBI_TAG:-latest}"
    volumes:
      - ${HOME}/logs:/logs
      - ./etc:/fluentd/etc
    ports:
      - "24225:24224"
      - "24225:24224/udp"
    logging:
      driver: local
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.1 24224 || exit 1" ]
      interval: 10s
      timeout: 10s
      start_period: 5s

#  opensearch-node:
#    image: opensearchproject/opensearch:2.1.0
#    environment:
#      - cluster.name=opensearch-cluster
#      - node.name=opensearch-node
#      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
#      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
#      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
#      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
#      - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
#    expose:
#      - "9200"
#    ports:
#      - "9200:9200"
#      - "9600:9600" # required for Performance Analyzer
#    volumes:
#      - opensearch-data:/usr/share/opensearch/data
#    healthcheck:
#      test:
#        [
#            "CMD-SHELL",
#            "curl --fail http://localhost:9200",
#        ]
#      interval: 10s
#      timeout: 10s
#      start_period: 5s
#      retries: 120
#
#  dashboard:
#    depends_on:
#      opensearch-node:
#        condition: service_healthy
#    image: opensearchproject/opensearch-dashboards:2.1.0
#    ports:
#      - 5601:5601
#    expose:
#      - "5601"
#    environment:
#      - 'OPENSEARCH_HOSTS=["http://opensearch-node:9200"]' # must be a string with no spaces when specified as an environment variable
#      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
#
#
#volumes:
#  opensearch-data:
